### ISSUE TITLE
Bindingjs does not work alongside backbone events

### ISSUE THREAD

**Issue by leonpegg** [rummelj/bindingjs#42]
Please see example attached with and without backbone events
http://jsfiddle.net/1Lqwv4yd/

**Comment by rummelj** [comment]
Both BindingJS and Backbone assume, that the element you provide is excluively for them. Backbone assumes that it is detached afaik and BindingJS just takes it and clones it to ensure that it is static through further processing. Thus the problem. I see two solutions for this:
1. Use Backbone initialize to set up BindingJS and set the element after BindingJS has activated the binding http://jsfiddle.net/e1fvomnf/ . I do not know Backbone very well - so I do not know if that is good practise
2. Pass the element to the view constructor after BindingJS was initialized.http://jsfiddle.net/avnLm525/2/ . Again I do not know if this satisfies your use case. Please let me know.

**Comment by rummelj** [comment]
By the way, if you face the problem of dependent view elements like in the example, there are two other ways to solve this:
1. By using `on:click` and the binding scope `@` http://jsfiddle.net/odmcpfvs/
2. By using sockets (Probably more intuitive with Iteration, but it works here too) http://jsfiddle.net/odmcpfvs/1/

**Comment by leonpegg** [comment]
the problem is that the events defined in the backbone view do not work when combined with bindingjs.
both the examples there is no backbone view with events.

**Comment by rummelj** [comment]
In my previous answer there are two examples of how you can realize events in Backbone together with BindingJS. My second answer is there to illustrate, that you can achieve the same thing with BindingJS only.

**Comment by leonpegg** [comment]
apologies only noticed the last reply not the one before I was in a rush will look over the solutions provided thanks

**Comment by leonpegg** [comment]
Thanks for the examples rummelj I have gone over them and http://jsfiddle.net/e1fvomnf/1/ is the solution I finally used.

I will now close this issue and thanks for the help
